# Generated by Django 4.2.29 on 2026-04-07 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=15)),
                ('hospital', models.CharField(max_length=20)),
                ('specialization', models.CharField(max_length=20)),
                ('mobile', models.BigIntegerField()),
                ('experience', models.CharField(max_length=20)),
            ],
        ),
    ]
