# Generated by Django 4.2.22 on 2026-05-12 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_docinfo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='docinfo',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='docinfo',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
